In [1]:
docs=[
    '먹고 싶은 사과',
    '먹고 싶은 바나나',
    '길고 노란 바나나 바나나',
    '저는 과일이 좋아요'
]

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()

In [3]:
# 문장을 벡터 형태로 변형
countVect=vect.fit_transform(docs)
countVect

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [4]:
countVect.toarray()

array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [5]:
vect.vocabulary_

{'먹고': 3,
 '싶은': 6,
 '사과': 5,
 '바나나': 4,
 '길고': 1,
 '노란': 2,
 '저는': 7,
 '과일이': 0,
 '좋아요': 8}

In [6]:
sorted(vect.vocabulary_)

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

In [7]:
import pandas as pd
countVect_df=pd.DataFrame(countVect.toarray(), columns=sorted(vect.vocabulary_))
countVect_df.index=['문서1','문서2','문서3','문서4']
countVect_df

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
문서1    0   0   0   1    0   1   1   0    0
문서2    0   0   0   1    1   0   1   0    0
문서3    0   1   1   0    2   0   0   0    0
문서4    1   0   0   0    0   0   0   1    1

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(countVect_df, countVect_df)

array([[1.        , 0.66666667, 0.        , 0.        ],
       [0.66666667, 1.        , 0.47140452, 0.        ],
       [0.        , 0.47140452, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

1번문서와 2번문서가 유사함을 살펴볼 수 있다.

2번문서와 3번문서가 유사함을 살펴볼 수 있다.

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
tfvect = vect.fit(docs)

In [14]:
tfidv_df = pd.DataFrame(tfvect.transform(docs).toarray(), columns = sorted(vect.vocabulary_))
tfidv_df.index = ['문서1', '문서2', '문서3', '문서4']
tfidv_df

과일이       길고       노란        먹고      바나나        사과        싶은  \
문서1  0.00000  0.00000  0.00000  0.526405  0.00000  0.667679  0.526405   
문서2  0.00000  0.00000  0.00000  0.577350  0.57735  0.000000  0.577350   
문서3  0.00000  0.47212  0.47212  0.000000  0.74445  0.000000  0.000000   
문서4  0.57735  0.00000  0.00000  0.000000  0.00000  0.000000  0.000000   

          저는      좋아요  
문서1  0.00000  0.00000  
문서2  0.00000  0.00000  
문서3  0.00000  0.00000  
문서4  0.57735  0.57735

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(tfidv_df, tfidv_df)

array([[1.        , 0.60784064, 0.        , 0.        ],
       [0.60784064, 1.        , 0.42980824, 0.        ],
       [0.        , 0.42980824, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])